# Generated by Django 2.1.7 on 2019-03-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('O', 'Ongoing')], max_length=1)),
                ('difficulty', models.FloatField(help_text='Chance of each square to be a mine')),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(default=20)),
                ('height', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('has_mine', models.BooleanField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Grid')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Grid'),
        ),
    ]
