# Generated by Django 2.1.7 on 2019-03-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_square_has_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
