# Generated by Django 2.1.7 on 2019-03-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_square_adjacent_mines'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='square',
            unique_together={('x', 'y', 'grid')},
        ),
    ]
