# Generated by Django 2.1.7 on 2019-03-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190301_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='grid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Grid'),
        ),
    ]
