# Generated by Django 2.1.7 on 2019-03-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190301_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='adjacent_mines',
        ),
    ]
