# Generated by Django 2.1.7 on 2019-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_square_adjacent_mines'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='adjacent_mines',
            field=models.SmallIntegerField(default=0),
        ),
    ]
